[package]
name = "af-mcp"
version = "0.1.0"
edition = "2021"

[dependencies]
mcp_daemon = "0.2.1"
futures-util = "0.3.31"
serde_json = "1.0.134"
tracing = "0.1.41"
tokio = "1.42.0"
anyhow = "1.0.97"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
dotenv = "0.15.0"
